CREATE TABLE PRODUTOS (

    CODIGO          INT         NOT NULL,
    DESCRICAO       VARCHAR(50) NOT NULL,
    DATA_VALIDADE   DATETIME,
    EAN             VARCHAR(15) NOT NULL,
    IND_INATIVO     INT         NOT NULL DEFAULT 0,

)
;

ALTER TABLE PRODUTOS
    ADD CONSTRAINT      PK_PRODUTOS
        PRIMARY KEY     (CODIGO)
;

CREATE INDEX IDX_PRODUTOS_EAN
    ON  PRODUTOS(EAN)
;

INSERT INTO PRODUTOS VALUES (1, 'Nome do Produto', GETDATE(), '1234567890', 0);

INSERT INTO PRODUTOS(CODIGO, DESCRICAO, EAN) VALUES (2, 'Nome do Produto 2', '1234567890');

SELECT  * 
    FROM PRODUTOS
 WHERE DESCRICAO LIKE '%Produto%'   
 ;

 SELECT COUNT(*) AS TOTAL
    FROM PRODUTOS;

CREATE TABLE LOJAS (

    CODIGO      INT         NOT NULL,
    NOME        VARCHAR(50) NOT NULL,
    IND_INATIVO INT         NOT NULL DEFAULT 0,
    CONSTRAINT LOJAS_PK PRIMARY KEY (CODIGO)

)
;


INSERT INTO LOJAS (CODIGO, NOME) VALUES (1000, 'Filial Votuporanga');
INSERT INTO LOJAS (CODIGO, NOME) VALUES (2000, 'Filial São Paulo');
INSERT INTO LOJAS (CODIGO, NOME) VALUES (3000, 'Filial São José do Rio Preto');

SELECT      CODIGO
    ,       NOME
    FROM    LOJAS
    WHERE   IND_INATIVO = 0;

CREATE TABLE ESTOQUE(

    CODIGO_PRODUTO  INT NOT NULL,
    CODIGO_LOJA     INT NOT NULL,
    QUANTIDADE      DECIMAL NOT NULL DEFAULT 0,
    CONSTRAINT ESTOQUE_PK PRIMARY KEY (CODIGO_PRODUTO, CODIGO_LOJA)

);

INSERT INTO ESTOQUE(CODIGO_PRODUTO, CODIGO_LOJA, QUANTIDADE) VALUES (1,1000, 10);

DELETE FROM ESTOQUE;

SELECT * FROM ESTOQUE;

ALTER TABLE ESTOQUE
    ADD CONSTRAINT FK_ESTOQUE_PRODUTOS
        FOREIGN KEY (CODIGO_PRODUTO)
        REFERENCES PRODUTOS(CODIGO);

ALTER TABLE ESTOQUE
    ADD CONSTRAINT FK_ESTOQUE_LOJAS
        FOREIGN KEY (CODIGO_LOJA)
        REFERENCES LOJAS(CODIGO);

SELECT E.CODIGO_LOJA
    , L.NOME
    , E.CODIGO_PRODUTO
    , P.DESCRICAO
    , E.QUANTIDADE
    FROM ESTOQUE E
    INNER JOIN LOJAS L
     ON E.CODIGO_LOJA = L.CODIGO
    INNER JOIN PRODUTOS P
     ON E.CODIGO_PRODUTO = P.CODIGO